name: loto_ro
description: LotoRO - Statistici și Generator Inteligent pentru Loterii Românești
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI și Design
  cupertino_icons: ^1.0.2
  glassmorphism: ^3.0.0
  
  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # Grafici și Vizualizare
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Utilitare
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP și API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Animații
  lottie: ^2.7.0
  confetti: ^0.7.0
  
  # Utilitare pentru date
  csv: ^5.0.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
